netbox_multicast_stream_mapping/urls.py
from django.urls import path
from netbox.views.generic import ObjectChangeLogView

from . import models, views

urlpatterns = (
    # Format Tags ------------------------------------------------------------------------------------------------------
    path('formats/', views.FormatListView.as_view(), name='format_list'),
    path('formats/add/', views.FormatEditView.as_view(), name='format_add'),
    path('formats/<int:pk>/', views.FormatView.as_view(), name='format'),
    path('formats/<int:pk>/edit/', views.FormatEditView.as_view(), name='format_edit'),
    path('formats/<int:pk>/delete/', views.FormatDeleteView.as_view(), name='format_delete'),
    path('formats/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='format_changelog',
         kwargs={'model': models.Format}),
    path('formats/delete/', views.FormatBulkDeleteView.as_view(), name='format_bulk_delete'),
    path('formats/edit/', views.FormatBulkEditView.as_view(), name='format_bulk_edit'),

    # Processor --------------------------------------------------------------------------------------------------------
    path('processors/', views.ProcessorListView.as_view(), name='processor_list'),
    path('processors/add/', views.ProcessorEditView.as_view(), name='processor_add'),
    path('processors/<int:pk>/', views.ProcessorView.as_view(), name='processor'),
    path('processors/<int:pk>/edit/', views.ProcessorEditView.as_view(), name='processor_edit'),
    path('processors/<int:pk>/delete/', views.ProcessorDeleteView.as_view(), name='processor_delete'),
    path("processors/<int:pk>/endpoints/", views.EndpointChildView.as_view(), name="endpoint_children"), # todo andere überschrift in dieser ansicht
    path('processors/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='processor_changelog',
         kwargs={'model': models.Processor}),
    path('processors/delete/', views.ProcessorBulkDeleteView.as_view(), name='processor_bulk_delete'),
    path('processors/edit/', views.ProcessorBulkEditView.as_view(), name='processor_bulk_edit'),

    # Endpoints --------------------------------------------------------------------------------------------------------
    path('endpoints/', views.EndpointListView.as_view(), name='endpoint_list'),
    path('endpoints/add/', views.EndpointEditView.as_view(), name='endpoint_add'),
    path('endpoints/<int:pk>/', views.EndpointView.as_view(), name='endpoint'),
    path('endpoints/<int:pk>/edit/', views.EndpointEditView.as_view(), name='endpoint_edit'),
    path('endpoints/<int:pk>/delete/', views.EndpointDeleteView.as_view(), name='endpoint_delete'),
    path('endpoints/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='endpoint_changelog',
         kwargs={'model': models.Endpoint}),
    path('endpoints/delete/', views.EndpointBulkDeleteView.as_view(), name='endpoint_bulk_delete'),
    path('endpoints/edit/', views.EndpointBulkEditView.as_view(), name='endpoint_bulk_edit'),

    # Stream -----------------------------------------------------------------------------------------------------------
    path('streams/', views.StreamListView.as_view(), name='stream_list'),
    path('streams/add/', views.StreamEditView.as_view(), name='stream_add'),
    path('streams/<int:pk>/', views.StreamView.as_view(), name='stream'),
    path('streams/<int:pk>/edit/', views.StreamEditView.as_view(), name='stream_edit'),
    path('streams/<int:pk>/delete/', views.StreamDeleteView.as_view(), name='stream_delete'),
    path('streams/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='stream_changelog',
         kwargs={'model': models.Stream}),
    path('streams/delete/', views.StreamBulkDeleteView.as_view(), name='stream_bulk_delete'),
    path('streams/edit/', views.StreamBulkEditView.as_view(), name='stream_bulk_edit'),

    # Other ------------------------------------------------------------------------------------------------------------
    path("devices/<int:pk>/processors/", views.DeviceProcessorView.as_view(), name="device_processors"),
    path("devices/<int:pk>/endpoints/", views.DeviceEndpointView.as_view(), name="device_endpoints"),

)

netbox_multicast_stream_mapping/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from utilities.choices import ChoiceSet
from netbox.models import NetBoxModel


# Choices --------------------------------------------------------------------------------------------------------------

# Choices for Endpoint Type -> Sender or Receiver?
class EndpointTypeChoices(ChoiceSet):
    key = 'Endpoint.endpoint_type'

    CHOICES = [
        ('sender', 'Sender', 'red'),
        ('receiver', 'Receiver', 'green'),
    ]


# Choices for Signal Type of Endpoint
class SignalTypeChoices(ChoiceSet):
    key = 'Endpoint.signal_type'

    CHOICES = [
        ('video', 'Video', 'blue'),
        ('audio', 'Audio', 'yellow'),
        ('metadata', 'Metadata', 'orange'),
    ]


# Choices for switch method (ST 2022-7)
class SwitchMethodChoices(ChoiceSet):
    key = 'Endpoint.switch_method'

    CHOICES = [
        ('sips_merge', 'SiPs Merge', 'cyan'),
        ('sips_split', 'SiPs Split', 'purple'),
    ]


# Choices for Signal Type of Format Preset
class FormatTypeChoices(ChoiceSet):
    key = 'Format.type'

    CHOICES = [
        ('video', 'Video', 'blue'),
        ('audio', 'Audio', 'yellow'),
        ('metadata', 'Metadata', 'orange'),
        ('ect', 'Ect.'),
    ]


# todo feste auswahloptionen fpr pixel, bandbreite, usw....
# choices for frame rates in Format Presets
class FpsChoices(ChoiceSet):
    key = 'Format.fps'

    CHOICES = [
        # progressive broadcast
        ('p25', 'p25'),
        ('p29.97', 'p29.97'),
        ('p30', 'p30'),
        ('p50', 'p50'),
        ('p59.94', 'p59.94'),
        ('p60', 'p60'),

        # interlaced broadcast
        ('i50', 'i50'),
        ('i59.94', 'i59.94'),
        ('i60', 'i60'),

        # high frame rate
        ('p100', 'p100'),
        ('p120', 'p120'),
        ('p144', 'p144'),
        ('p180', 'p180'),
        ('p240', 'p240'),
    ]


# Models ---------------------------------------------------------------------------------------------------------------

# model format presets -> are supported for endpoints
class Format(NetBoxModel):
    name = models.CharField(max_length=100)
    type = models.CharField(choices=FormatTypeChoices, null=True, blank=True)
    res_h = models.PositiveIntegerField(null=True, blank=True)
    res_w = models.PositiveIntegerField(null=True, blank=True)
    fps = models.CharField(choices=FpsChoices, null=True, blank=True)
    audio_ch = models.PositiveIntegerField(null=True, blank=True)
    port = models.PositiveIntegerField(null=True, blank=True) # todo min/max?
    comments = models.TextField(blank=True)
    description = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ("name",)
        unique_together = ("name",)

    # returns human readable name
    def __str__(self):
        return self.name

    # django convention for URL mapping
    def get_absolute_url(self):
        return reverse('plugins:netbox_multicast_stream_mapping:format', args=[self.pk])

    # returns badge color for multiple choice fields
    def get_type_color(self):
        return FormatTypeChoices.colors.get(self.type)


# model for internal processing units of devices -> has senders and receivers
class Processor(NetBoxModel): # todo device spalte anzahl an enpoints oder procs?
    name = models.CharField(max_length=100) # todo in tabellenansicht aus gerät auch device namen anzeigen?
    device = models.ForeignKey(to='dcim.Device', on_delete=models.CASCADE, related_name='+') # todo related_name='+' um keine beziehung rückwärst zu erstellen
    module = models.ForeignKey(to='dcim.Module', on_delete=models.CASCADE, related_name='+', null=True, blank=True) # todo logik -> modul muss zu device gehören
    description = models.CharField(max_length=500, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ("name",)
        unique_together = ("name",)
        # TODO mehr?

    # returns human readable name
    def __str__(self):
        return self.name

    # django convention for URL mapping
    def get_absolute_url(self):
        return reverse('plugins:netbox_multicast_stream_mapping:processor', args=[self.pk])

    # function to get number of endpoints for detail view template
    def get_endpoint_count(self):
        return self.endpoint_set.count()


# model for internal processing units of devices -> has senders and receivers
class Endpoint(NetBoxModel):
    name = models.CharField(max_length=100)
    device = models.ForeignKey(to='dcim.Device', on_delete=models.CASCADE, null=True, related_name='+') # todo related_name='+' um keine beziehung rückwärst zu erstellen
    processor = models.ForeignKey(to=Processor, on_delete=models.CASCADE)
    interface = models.ForeignKey(to='dcim.Interface', on_delete=models.SET_NULL, related_name='+', blank=True, null=True) # todo gleiche ip mehrfach! oder range?
    endpoint_type = models.CharField(choices=EndpointTypeChoices, null=True) # todo farben als plakette
    primary_ip = models.OneToOneField(to='ipam.IPAddress', on_delete=models.SET_NULL, related_name='+', blank=True, null=True) # todo gleiche ip mehrfach! oder range?
    secondary_ip = models.OneToOneField(to='ipam.IPAddress', on_delete=models.SET_NULL, related_name='+', blank=True, null=True)
    max_bandwidth = models.FloatField(null=True, blank=True)
    supported_formats = models.ManyToManyField(to=Format, blank=True) # todo filter basiert auf signal type?
    switch_method = models.CharField(choices=SwitchMethodChoices, null=True, blank=True) # todo plakette
    signal_type = models.CharField(choices=SignalTypeChoices, null=True, blank=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    comments = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ("name",)
        unique_together = ("name",)
        # todo mehr ?

    # returns human readable name
    def __str__(self):
        return self.name

    # django convention for URL mapping
    def get_absolute_url(self):
        return reverse('plugins:netbox_multicast_stream_mapping:endpoint', args=[self.pk])

    # returns badge color for multiple choice fields
    def get_signal_type_color(self):
        return SignalTypeChoices.colors.get(self.signal_type)

    # returns badge color for multiple choice fields
    def get_switch_method_color(self):
        return SwitchMethodChoices.colors.get(self.switch_method)

    # returns badge color for multiple choice fields
    def get_endpoint_type_color(self):
        return EndpointTypeChoices.colors.get(self.endpoint_type)


# model for internal processing units of devices -> has senders and receivers
class Stream(NetBoxModel):
    name = models.CharField(max_length=100)
    sender = models.ForeignKey(to=Endpoint, on_delete=models.CASCADE, related_name="sent_streams")
    receivers = models.ManyToManyField(to=Endpoint, related_name="received_streams")
    bandwidth = models.FloatField(null=True, blank=True)
    signal_type = models.CharField(choices=SignalTypeChoices, null=True, blank=True)
    protocol = models.CharField(max_length=100, blank=True)  # todo choice -> welche?
    formats = models.ManyToManyField(to=Format, blank=True)
    comments = models.TextField(blank=True)
    description = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ("name",)
        unique_together = ("name",)

    # returns human readable name
    def __str__(self):
        return self.name

    # django convention for URL mapping
    def get_absolute_url(self):
        return reverse('plugins:netbox_multicast_stream_mapping:stream', args=[self.pk])

    # returns badge color for multiple choice fields
    def get_signal_type_color(self):
        return SignalTypeChoices.colors.get(self.signal_type)

netbox_multicast_stream_mapping/templates/netbox_multicast_stream_mapping/endpoint.html
{% extends 'generic/object.html' %}


{% block content %}
  <div class="row mb-3">

    <div class="col col-md-6">

      <div class="card">
        <h5 class="card-header">Endpoint</h5>
        <div class="card-body">

          <table class="table table-hover attr-table">

            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name|linkify }}</td>
            </tr>

            <tr>
              <th scope="row">Signal Type</th>
              <td>{{ object.get_signal_type_display|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Device</th>
              <td>{{ object.device|linkify }}</td>
            </tr>

            <tr>
              <th scope="row">Processor</th>
              <td>{{ object.processor|linkify }}</td>
            </tr>

            <tr>
              <th scope="row">Interface</th>
              <td>{{ object.interface|linkify }}</td>
            </tr>

            <tr>
              <th scope="row">Endpoint Type</th>
              <td>{{ object.get_endpoint_type_display }}</td>
            </tr>

            <tr>
              <th scope="row">Primary IP Address</th>
              <td>{{ object.primary_ip|linkify|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Secondary IP Address</th>
              <td>{{ object.secondary_ip|linkify|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Max. Bandwidth (Mbps) </th>
              <td>{{ object.max_bandwidth|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Switch Method (2022-7) </th>
              <td>{{ object.get_switch_method_display|placeholder }}</td>
            </tr>

          </table>

        </div>
      </div>
      </div>

    <div class="col col-md-6">

      <div class="card">
        <h5 class="card-header">Supported Formats</h5>
        <div class="card-body">

          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Supported Formats</th>
              <td>
                {% if object.supported_formats.all %}
                  {% for format in object.supported_formats.all %}
                    {{ format|linkify }}
                    {% if not forloop.last %},&nbsp;{% endif %}
                  {% endfor %}
                {% else %}
                   —
                {% endif %}
              </td>
            </tr>
          </table>

        </div>

    </div>
          {% include 'inc/panels/tags.html' %}
          {% include 'inc/panels/comments.html' %}
          {% include 'inc/panels/custom_fields.html' %}
  </div>
{% endblock content %}

netbox_multicast_stream_mapping/templates/netbox_multicast_stream_mapping/endpoint_list.html
{% extends 'generic/object_children.html' %}
{% load i18n %}

{% block title %}
   Endpoints of Processor {{ object.name }}
{% endblock title %}

{% block extra_controls %}
{% endblock extra_controls %}

netbox_multicast_stream_mapping/templates/netbox_multicast_stream_mapping/format.html
{% extends 'generic/object.html' %}


{% block content %}
  <div class="row mb-3">

    <div class="col col-md-6">

      <div class="card">
        <h5 class="card-header">Format</h5>
        <div class="card-body">

          <table class="table table-hover attr-table">

            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name }}</td>
            </tr>

            <tr>
              <th scope="row">Type</th>
              <td>{{ object.get_type_display|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Vertical Resolution</th>
              <td>{{ object.res_h|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Horizontal Resolution</th>
              <td>{{ object.res_w|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Frame Rate</th>
              <td>{{ object.fps|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Number of Audio Channels </th>
              <td>{{ object.audio_ch|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Network Port </th>
              <td>{{ object.port|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Description </th>
              <td>{{ object.description|placeholder }}</td>
            </tr>

          </table>

        </div>
      </div>
      </div>

    <div class="col col-md-6">
          {% include 'inc/panels/tags.html' %}
          {% include 'inc/panels/comments.html' %}
          {% include 'inc/panels/custom_fields.html' %}
    </div>
  </div>
{% endblock content %}

netbox_multicast_stream_mapping/templates/netbox_multicast_stream_mapping/processor.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="row mb-3">

    <div class="col col-md-6">

      <div class="card">
        <h5 class="card-header">Processor</h5>
        <div class="card-body">

          <table class="table table-hover attr-table">

            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name|linkify }}</td>
            </tr>

            <tr>
              <th scope="row">Device</th>
              <td>{{ object.device|linkify|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Module</th>
              <td>{{ object.module|linkify|placeholder }}</td>
            </tr>

            <tr>
                <th scope="row">Number of Endpoints</th>
                <td><a href="{% url 'plugins:netbox_multicast_stream_mapping:endpoint_children' object.pk %}">{{ object.get_endpoint_count }}</a></td>
            </tr>

          </table>

        </div>
      </div>

    </div>

    <div class="col col-md-6">
      {% include 'inc/panels/tags.html' %}
      {% include 'inc/panels/comments.html' %}
      {% include 'inc/panels/custom_fields.html' %}

    </div>
  </div>

<div class="card">
        <h5 class="card-header">Endpoints</h5>
        <div class="card-body">
        <div class="card-body table-responsive">
          {% render_table endpoints_table %}
        </div>
        </div>
      </div>

{% endblock content %}

netbox_multicast_stream_mapping/templates/netbox_multicast_stream_mapping/processor_list.html
{% extends 'generic/object_children.html' %}
{% load i18n %}

{% block extra_controls %}
<!--# TODO logik, buttons, usw-->
{% endblock extra_controls %}

netbox_multicast_stream_mapping/templates/netbox_multicast_stream_mapping/receiver.html
{% extends 'generic/object.html' %}

<!--TODO: Add Rules Table -> in Views ergänzen -< context data -> context variable -->
<!--TODO: get_absolute_url; placeholder; protocol/action -> funktion schritt 6 -->

{% block content %}
  <div class="row mb-3">

    <div class="col col-md-6">

      <div class="card">
        <h5 class="card-header">Receiver</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/tags.html' %}
      {% include 'inc/panels/comments.html' %}
      {% include 'inc/panels/custom_fields.html' %}
    </div>

    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Streams</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
              <tr>
              <th scope="row">Platzhalter</th>
              <td>{{ "Platzhalter" }}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

netbox_multicast_stream_mapping/templates/netbox_multicast_stream_mapping/stream.html
{% extends 'generic/object.html' %}


{% block content %}
  <div class="row mb-3">

    <div class="col col-md-6">

      <div class="card">
        <h5 class="card-header">Stream</h5>
        <div class="card-body">

          <table class="table table-hover attr-table">

            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name }}</td>
            </tr>

            <tr>
              <th scope="row">Sender</th>
              <td>{{ object.sender|linkify }}</td>
            </tr>

<!--              todo dateteyp und link-->
            <tr>
              <th scope="row">Receivers</th>
              <td>
                {% if object.receivers.all %}
                  {% for receivers in object.receivers.all %}
                    {{ receivers|linkify }}
                    {% if not forloop.last %},&nbsp;{% endif %}
                  {% endfor %}
                {% else %}
                   —
                {% endif %}
              </td>
            </tr>

            <tr>
              <th scope="row">Bandwidth</th>
              <td>{{ object.bandwidth|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Signal Type</th>
              <td>{{ object.get_signal_type_display|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Protocol</th>
              <td>{{ object.protocol|placeholder }}</td>
            </tr>

            <tr>
              <th scope="row">Formats</th>
              <td>
                {% if object.formats.all %}
                  {% for formats in object.formats.all %}
                    {{ formats|linkify }}
                    {% if not forloop.last %},&nbsp;{% endif %}
                  {% endfor %}
                {% else %}
                   —
                {% endif %}
              </td>
            </tr>

          </table>

        </div>
      </div>
      </div>

    <div class="col col-md-6">

          {% include 'inc/panels/tags.html' %}
          {% include 'inc/panels/comments.html' %}
          {% include 'inc/panels/custom_fields.html' %}
  </div>
{% endblock content %}